default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: nippo_development

test:
  <<: *default
  database: nippo_test

production:
  <<: *default
  database: nippo_production
  username: nippo
  password: <%= ENV['NIPPO_DATABASE_PASSWORD'] %>
